[source.crates-io]
# registry = "https://github.com/rust-lang/crates.io-index"
replace-with = 'tuna'

# cargo info mdman --registry tuna
[source.tuna]
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"
[registries.tuna]
index = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"
[registries.ustc]
index = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

# cargo <= 1.68
# [source.tuna]
# registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"
# [source.ustc]
# registry = "git://mirrors.ustc.edu.cn/crates.io-index"

[net]
git-fetch-with-cli = true

# use CARGO_BUILD_TARGET_DIR to specify the target directory
# [build]
# # base target directory: ~/.target, work.
# target-dir = ".target"

# [install]
# # build binary to ~/.local/bin, cann't work!
# root = ".local"
