---

- name: Install nginx proxy
  tags:
    - ssproxy
  block:

    - name: Install nginx package
      ansible.builtin.dnf:
        name:
          - nginx
          - nginx-mod-stream
        state: present  # Ensures the package is installed

    - name: Copy nginx.conf file
      ansible.builtin.copy:
        src: ~/.local/etc/ss-nginx-proxy.conf
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      register: nginxconf_copy_result  # Register the result to a variable

    - name: Ensure nginx service is running and enabled
      ansible.builtin.systemd_service:
        name: nginx
        state: started
        enabled: true

    - name: Reload nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: reloaded
        daemon_reload: true
      when: nginxconf_copy_result.changed
